CREATE PROCEDURE DROP_ALL
AS
BEGIN

--LANDING LAYER
DROP TABLE IF EXISTS NW_LANDING.LND_Categories;
DROP TABLE IF EXISTS NW_LANDING.LND_CustomerCustomerDemo;
DROP TABLE IF EXISTS NW_LANDING.LND_CustomerDemographics;
DROP TABLE IF EXISTS NW_LANDING.LND_Customers;
DROP TABLE IF EXISTS NW_LANDING.LND_Employees;
DROP TABLE IF EXISTS NW_LANDING.LND_EmployeeTerritories;
DROP TABLE IF EXISTS NW_LANDING.[LND_Order Details];
DROP TABLE IF EXISTS NW_LANDING.LND_Orders;
DROP TABLE IF EXISTS NW_LANDING.LND_Products;
DROP TABLE IF EXISTS NW_LANDING.LND_Region;
DROP TABLE IF EXISTS NW_LANDING.LND_Shippers;
DROP TABLE IF EXISTS NW_LANDING.LND_Suppliers;
DROP TABLE IF EXISTS NW_LANDING.LND_Territories;

--STAGING LAYER
DROP TABLE IF EXISTS NW_STAGING.STG_Customers;
DROP TABLE IF EXISTS NW_STAGING.STG_Employees;
DROP TABLE IF EXISTS NW_STAGING.STG_Categories;
DROP TABLE IF EXISTS NW_STAGING.STG_Products;
DROP TABLE IF EXISTS NW_STAGING.STG_Suppliers;
DROP TABLE IF EXISTS NW_STAGING.[STG_Order Details];
DROP TABLE IF EXISTS NW_STAGING.STG_Orders;

--DATAWAREHOUSE LAYER
DROP TABLE IF EXISTS NW_DW.CustomerEmployee_Fact;
DROP TABLE IF EXISTS NW_DW.ProductInStock_Fact;
DROP TABLE IF EXISTS NW_DW.Calender_DIM;
DROP TABLE IF EXISTS NW_DW.Customer_DIM;
DROP TABLE IF EXISTS NW_DW.Employee_DIM;
DROP TABLE IF EXISTS NW_DW.Categories_DIM;
DROP TABLE IF EXISTS NW_DW.Product_DIM;
DROP TABLE IF EXISTS NW_DW.Supplier_DIM;

END


EXEC DROP_ALL
DROP PROCEDURE DROP_ALL